apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langgraph-postgres-data-nik
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langgraph-redis-data-nik
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-data
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.seaweedfs.storage }}