apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seaweedfs
  template:
    metadata:
      labels:
        app: seaweedfs
    spec:
      containers:
      - name: seaweedfs
        image: "{{ .Values.seaweedfs.image.repository }}:{{ .Values.seaweedfs.image.tag }}"
        command: ["/usr/bin/weed"]
        args:
        - "server"
        - "-dir=/data"
        - "-filer=true"
        - "-s3=true"
        - "-master.volumeSizeLimitMB=1024"
        - "-volume.max=0"
        - "-s3.port=8333"
        ports:
        - containerPort: 8333
        - containerPort: 9333
        - containerPort: 8888
        volumeMounts:
        - mountPath: /data
          name: seaweedfs-data
          subPath: data
        resources:
{{ toYaml .Values.seaweedfs.resources | indent 10 }}
      volumes:
      - name: seaweedfs-data
        persistentVolumeClaim:
          claimName: seaweedfs-data
---
apiVersion: v1
kind: Service
metadata:
  name: seaweedfs
spec:
  selector:
    app: seaweedfs
  ports:
  - name: s3
    port: 8333
    targetPort: 8333
  - name: master
    port: 9333
    targetPort: 9333
  - name: filer-ui
    port: 8888
    targetPort: 8888ss